version: '3'

services:
  app:
    build:
      context: .
      target: dev  # Use 'dev' for development, 'runner' for production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
